CREATE TABLE CLASS_PERIOD(
 id            SERIAL  PRIMARY KEY,
CLASS_ID       BIGINT NOT NULL,
PERIOD_ID      BIGINT NOT NULL,
active_status BOOLEAN DEFAULT TRUE,
FOREIGN KEY(CLASS_ID) REFERENCES classes(id),
FOREIGN KEY(PERIOD_ID) REFERENCES PERIOD_RELATIONSHIP(id)
);