DROP TABLE user_details CASCADE;
DROP TABLE USERS CASCADE;
DROP TABLE USER_ROLE CASCADE;
DROP TABLE USER_OTP CASCADE;
DROP TABLE USER_ROLE_TYPE CASCADE;
DROP TABLE SEND_EMAIL_TYPE CASCADE;
DROP TABLE SEND_EMAIL CASCADE;
