CREATE TABLE INSTRUCTOR_ORGANIZATION(
id            SERIAL       PRIMARY KEY,
USER_ID       BIGINT       NOT     NULL , 
generated_on  TIMESTAMP    DEFAULT now(),
org_active    BOOLEAN      DEFAULT TRUE,
FOREIGN KEY(USER_ID) REFERENCES USERS(id),
org_name      VARCHAR(128) NOT NULL UNIQUE
);
