
CREATE  TABLE SEND_EMAIL(
id            SERIAL       PRIMARY KEY,
status     SMALLINT DEFAULT 1,
email       VARCHAR(100)     NOT NULL,
created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
send_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email_type SMALLINT NOT NULL ,
FOREIGN KEY(email_type) REFERENCES SEND_EMAIL_TYPE(id),
data JSONB DEFAULT '{}',
status_code SMALLINT DEFAULT -1 NOT NULL,
reason VARCHAR(100)
);
