CREATE  TABLE USER_OTP(
id            SERIAL       PRIMARY KEY ,
OTP     SMALLINT  ,
USER_ID BIGINT,
generated_on TIMESTAMP DEFAULT now(),
OTP_TRIED_FOR SMALLINT CHECK(OTP_TRIED_FOR<5) DEFAULT 0,
OTP_ACTIVE BOOLEAN DEFAULT TRUE
);